# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in tic_tac_toe.gemspec
gemspec

gem "irb"
gem "yaml"
gem "rake", "~> 13.0"
gem "dotenv"
gem "minitest", "~> 5.16"

gem 'telegram-bot-ruby'
